// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIEWDmbkitoIAFlf7nbIKYcr0HFQ31Y2k',
    appId: '1:901424403199:web:9d98e4cf18715cb01df2ca',
    messagingSenderId: '901424403199',
    projectId: 'icaroproagro-612d3',
    authDomain: 'icaroproagro-612d3.firebaseapp.com',
    storageBucket: 'icaroproagro-612d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXhC02lkkYwooAxYM0Tz3jL8Jbp3mOwnI',
    appId: '1:901424403199:android:5c2400e07bf717921df2ca',
    messagingSenderId: '901424403199',
    projectId: 'icaroproagro-612d3',
    storageBucket: 'icaroproagro-612d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_3tA7IiulKSxyFcRYjjvF2KNg9D5XG0Q',
    appId: '1:901424403199:ios:e5b3d9f61508abd11df2ca',
    messagingSenderId: '901424403199',
    projectId: 'icaroproagro-612d3',
    storageBucket: 'icaroproagro-612d3.firebasestorage.app',
    iosClientId: '901424403199-dq9sigcmf3sdrt3p695p9rhj4at3jqnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dronesFumigacionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_3tA7IiulKSxyFcRYjjvF2KNg9D5XG0Q',
    appId: '1:901424403199:ios:e5b3d9f61508abd11df2ca',
    messagingSenderId: '901424403199',
    projectId: 'icaroproagro-612d3',
    storageBucket: 'icaroproagro-612d3.firebasestorage.app',
    iosClientId: '901424403199-dq9sigcmf3sdrt3p695p9rhj4at3jqnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dronesFumigacionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIEWDmbkitoIAFlf7nbIKYcr0HFQ31Y2k',
    appId: '1:901424403199:web:a14e3a456be2b0911df2ca',
    messagingSenderId: '901424403199',
    projectId: 'icaroproagro-612d3',
    authDomain: 'icaroproagro-612d3.firebaseapp.com',
    storageBucket: 'icaroproagro-612d3.firebasestorage.app',
  );
}
